
package types;

import java.util.HashMap;
import java.util.Map;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;


/**
 * Event
 * <p>
 * event object describes event information
 * 
 */
public class Event {

    /**
     * event Id is generated by system
     * 
     */
    private String eventId;
    /**
     * event name entered by user (repeatable)
     * (Required)
     * 
     */
    private String eventname;
    /**
     * the starter user id
     * (Required)
     * 
     */
    private String starterId;
    /**
     * Event Type
     * <p>
     * valid Type enum
     * (Required)
     * 
     */
    private Event.Type type;
    /**
     * DD/MM/YYYY
     * 
     */
    private String date;
    /**
     * the event start time(multiple of quarter)
     * 
     */
    private int start;
    /**
     * the total time(multiple of quarter)
     * 
     */
    private int count;
    /**
     * Event Repeat
     * <p>
     * valid Repeat enum
     * 
     */
    private Event.Repeat repeat;
    /**
     * event occurs location
     * 
     */
    private String location;
    /**
     * Event State
     * <p>
     * valid State enum
     * 
     */
    private Event.State state;
    /**
     * event description
     * 
     */
    private String description;

    /**
     * event Id is generated by system
     * 
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * event Id is generated by system
     * 
     */
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    public Event withEventId(String eventId) {
        this.eventId = eventId;
        return this;
    }

    /**
     * event name entered by user (repeatable)
     * (Required)
     * 
     */
    public String getEventname() {
        return eventname;
    }

    /**
     * event name entered by user (repeatable)
     * (Required)
     * 
     */
    public void setEventname(String eventname) {
        this.eventname = eventname;
    }

    public Event withEventname(String eventname) {
        this.eventname = eventname;
        return this;
    }

    /**
     * the starter user id
     * (Required)
     * 
     */
    public String getStarterId() {
        return starterId;
    }

    /**
     * the starter user id
     * (Required)
     * 
     */
    public void setStarterId(String starterId) {
        this.starterId = starterId;
    }

    public Event withStarterId(String starterId) {
        this.starterId = starterId;
        return this;
    }

    /**
     * Event Type
     * <p>
     * valid Type enum
     * (Required)
     * 
     */
    public Event.Type getType() {
        return type;
    }

    /**
     * Event Type
     * <p>
     * valid Type enum
     * (Required)
     * 
     */
    public void setType(Event.Type type) {
        this.type = type;
    }

    public Event withType(Event.Type type) {
        this.type = type;
        return this;
    }

    /**
     * DD/MM/YYYY
     * 
     */
    public String getDate() {
        return date;
    }

    /**
     * DD/MM/YYYY
     * 
     */
    public void setDate(String date) {
        this.date = date;
    }

    public Event withDate(String date) {
        this.date = date;
        return this;
    }

    /**
     * the event start time(multiple of quarter)
     * 
     */
    public int getStart() {
        return start;
    }

    /**
     * the event start time(multiple of quarter)
     * 
     */
    public void setStart(int start) {
        this.start = start;
    }

    public Event withStart(int start) {
        this.start = start;
        return this;
    }

    /**
     * the total time(multiple of quarter)
     * 
     */
    public int getCount() {
        return count;
    }

    /**
     * the total time(multiple of quarter)
     * 
     */
    public void setCount(int count) {
        this.count = count;
    }

    public Event withCount(int count) {
        this.count = count;
        return this;
    }

    /**
     * Event Repeat
     * <p>
     * valid Repeat enum
     * 
     */
    public Event.Repeat getRepeat() {
        return repeat;
    }

    /**
     * Event Repeat
     * <p>
     * valid Repeat enum
     * 
     */
    public void setRepeat(Event.Repeat repeat) {
        this.repeat = repeat;
    }

    public Event withRepeat(Event.Repeat repeat) {
        this.repeat = repeat;
        return this;
    }

    /**
     * event occurs location
     * 
     */
    public String getLocation() {
        return location;
    }

    /**
     * event occurs location
     * 
     */
    public void setLocation(String location) {
        this.location = location;
    }

    public Event withLocation(String location) {
        this.location = location;
        return this;
    }

    /**
     * Event State
     * <p>
     * valid State enum
     * 
     */
    public Event.State getState() {
        return state;
    }

    /**
     * Event State
     * <p>
     * valid State enum
     * 
     */
    public void setState(Event.State state) {
        this.state = state;
    }

    public Event withState(Event.State state) {
        this.state = state;
        return this;
    }

    /**
     * event description
     * 
     */
    public String getDescription() {
        return description;
    }

    /**
     * event description
     * 
     */
    public void setDescription(String description) {
        this.description = description;
    }

    public Event withDescription(String description) {
        this.description = description;
        return this;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this).append("eventId", eventId).append("eventname", eventname).append("starterId", starterId).append("type", type).append("date", date).append("start", start).append("count", count).append("repeat", repeat).append("location", location).append("state", state).append("description", description).toString();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder().append(date).append(eventId).append(starterId).append(repeat).append(start).append(count).append(description).append(location).append(state).append(type).append(eventname).toHashCode();
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Event) == false) {
            return false;
        }
        Event rhs = ((Event) other);
        return new EqualsBuilder().append(date, rhs.date).append(eventId, rhs.eventId).append(starterId, rhs.starterId).append(repeat, rhs.repeat).append(start, rhs.start).append(count, rhs.count).append(description, rhs.description).append(location, rhs.location).append(state, rhs.state).append(type, rhs.type).append(eventname, rhs.eventname).isEquals();
    }

    public enum Repeat {

        ONCE("ONCE"),
        DAY("DAY"),
        WEEK("WEEK"),
        MONTH("MONTH"),
        YEAR("YEAR");
        private final String value;
        private final static Map<String, Event.Repeat> CONSTANTS = new HashMap<String, Event.Repeat>();

        static {
            for (Event.Repeat c: values()) {
                CONSTANTS.put(c.value, c);
            }
        }

        private Repeat(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return this.value;
        }

        public String value() {
            return this.value;
        }

        public static Event.Repeat fromValue(String value) {
            Event.Repeat constant = CONSTANTS.get(value);
            if (constant == null) {
                throw new IllegalArgumentException(value);
            } else {
                return constant;
            }
        }

    }

    public enum State {

        CANCELLED("CANCELLED"),
        ACTIVE("ACTIVE");
        private final String value;
        private final static Map<String, Event.State> CONSTANTS = new HashMap<String, Event.State>();

        static {
            for (Event.State c: values()) {
                CONSTANTS.put(c.value, c);
            }
        }

        private State(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return this.value;
        }

        public String value() {
            return this.value;
        }

        public static Event.State fromValue(String value) {
            Event.State constant = CONSTANTS.get(value);
            if (constant == null) {
                throw new IllegalArgumentException(value);
            } else {
                return constant;
            }
        }

    }

    public enum Type {

        WORK("WORK"),
        STUDY("STUDY"),
        ENTERTAINMENT("ENTERTAINMENT"),
        APPOINTMENT("APPOINTMENT"),
        OTHER("OTHER");
        private final String value;
        private final static Map<String, Event.Type> CONSTANTS = new HashMap<String, Event.Type>();

        static {
            for (Event.Type c: values()) {
                CONSTANTS.put(c.value, c);
            }
        }

        private Type(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return this.value;
        }

        public String value() {
            return this.value;
        }

        public static Event.Type fromValue(String value) {
            Event.Type constant = CONSTANTS.get(value);
            if (constant == null) {
                throw new IllegalArgumentException(value);
            } else {
                return constant;
            }
        }

    }

}
